### ISSUE TITLE
What are the expected results of the compatibility test

### ISSUE THREAD

**Issue by paynetechnologies** [amazonwebservices/aws-sdk-for-php#55]
Hi,

I downloaded to my Windows XP box where I have xampp and opened a browser as 

localhost/sdk_compatibility_test.php

What results should I expect after running this php file?

Thanks in advance,
Howard

**Comment by mtdowling** [comment]
When run, it will output a list of requirements and whether or not your system meets the requirements. You can review the results and install packages as needed. There should be a summary that will tell you whether or not your system is capable of running the SDK.
