### ISSUE TITLE
Unable to install with composer

### ISSUE THREAD

**Issue by yalamber** [amazonwebservices/aws-sdk-for-php#58]
Hello,
I am getting following message. I am having this issue on mac. Linux server was able to install the sdk through composer.
Updating dependencies (including require-dev)
- Installing aws/aws-sdk-php (2.4.2)
  Downloading: 100%         
  
  [UnexpectedValueException]  
  '/Users/xyz/Sites/works/vendor/aws/aws-sdk-php/ed  
  a362215aae6a8698f234ad073454f0.2' is not a zip archive.

**Comment by mtdowling** [comment]
This sounds like it's probably a transient error. Can you try deleting your composer.lock file and your vendor folder?

If that doesn't work: Which version of Composer are you using? Have you tried updating composer using `composer.phar self-update`?

**Comment by yalamber** [comment]
I tried now and it worked as normal. My composer was up to date. I also opened this issue at https://github.com/composer/composer/issues/2125 and they have added some debug code. May be this was issue related more to composer than aws sdk.
