### ISSUE TITLE
Please can you create a tag for the latest merged pull requests?

### ISSUE THREAD

**Issue by toby-griffiths** [amazonwebservices/aws-sdk-for-php#73]
I've just found this merged pull request when looking for a fix to the "Use of undefined constant CURLOPT_CLOSEPOLICY" problem when running our code on a new box...

https://github.com/amazonwebservices/aws-sdk-for-php/pull/71

As we're using the `cybernox/amazon-webservices-bundle` Symfony bundle package in our project it's not pulling in this update.  Please can you tag this so that this patch it can be included?

**Comment by jeremeamia** [comment]
Done via [v1.6.3](https://github.com/amazonwebservices/aws-sdk-for-php/releases/tag/1.6.3).

**Comment by toby-griffiths** [comment]
Thank you.  Lovely and quick :relieved:
