### ISSUE TITLE
Support China region?

### ISSUE THREAD

**Issue by wow3065** [amazonwebservices/aws-sdk-for-php#79]
Hi 

I can't find china region(cn-north-1)'s setting in ec2 service?
this sdk not support china region?

Thank You

**Comment by jasonrundell** [comment]
AWS does not support a cn-north-1 region. Here are a list of the regions and services supported: https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/

**Comment by wow3065** [comment]
@jasonrundell 
Thank you for answer.
